# Generated by Django 4.1.7 on 2023-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='apellido',
            field=models.CharField(default='empty', max_length=40),
            preserve_default=False,
        ),
    ]
