# Generated by Django 4.1.7 on 2023-03-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='apellido',
        ),
    ]
