# Generated by Django 4.1.7 on 2023-03-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_remove_curso_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(unique=True),
        ),
    ]
